spring:

  # normal config
  application:
    name: tutorial-blog-web

  # for datasource config
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:${MYSQL_DB_PORT:3306}/t_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_DB_USER:root}
    password: ${MYSQL_DB_PASSWORD:root}

  # for flyway config
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  # for jackson config
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # for redis config
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # max connections
        max-active: 8
        # max wait time: if value < 0, meaning for no limits
        max-wait: -1ms
        # max idle connections
        max-idle: 8
        # min idle connections
        min-idle: 0

  # for cache config
  cache:
    type: redis
    # ttl set to 1 day
    time-to-live: 1d
    # using key prefix or not
    use-key-prefix: true
    # caffeine config, open record stats
    caffeine:
      spec: maximumSize=500, expireAfterAccess=600s, recordStats

# for server config
server:
  port: 16601
  servlet:
    context-path: /api/t-blog/


# for mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath: mappers/*.xml
  type-aliases-package: com.douyasi.tutorial.blog.domain.dao

# for logging config
debug: true
logging:
  charset:
    console: UTF-8
  level:
    root: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web: ERROR
    # self package logging level
    com.douyasi.tutorial.blog: DEBUG
  #//pattern:
    #// file: %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
    #// console: %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n

# swagger user defined property
swagger2:
  enabled: true